/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventorymanagement.view;

import inventorymanagement.controller.backACtionController;
import inventorymanagement.controller.inventoryController;
import inventorymanagement.controller.logoutController;

/**
 *
 * @author hopeless
 */
public class inventory extends javax.swing.JFrame {

    /**
     * Creates new form inventory
     */
    public inventory() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inTable = new javax.swing.JTable();
        showInventory = new javax.swing.JButton();
        clothes = new javax.swing.JCheckBox();
        grocery = new javax.swing.JCheckBox();
        cosmetics = new javax.swing.JCheckBox();
        snacks = new javax.swing.JCheckBox();
        toiletries = new javax.swing.JCheckBox();
        electronics = new javax.swing.JCheckBox();
        clear = new javax.swing.JButton();
        back = new javax.swing.JButton();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(59, 103, 142));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        inTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(inTable);

        showInventory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Inventory-maintenance-icon.png"))); // NOI18N
        showInventory.setText("Show Inventory");
        showInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showInventoryActionPerformed(evt);
            }
        });

        clothes.setBackground(new java.awt.Color(59, 103, 142));
        buttonGroup.add(clothes);
        clothes.setForeground(new java.awt.Color(255, 255, 255));
        clothes.setText("clothes");
        clothes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clothesActionPerformed(evt);
            }
        });

        grocery.setBackground(new java.awt.Color(59, 103, 142));
        buttonGroup.add(grocery);
        grocery.setForeground(new java.awt.Color(255, 255, 255));
        grocery.setText("grocery");
        grocery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groceryActionPerformed(evt);
            }
        });

        cosmetics.setBackground(new java.awt.Color(59, 103, 142));
        buttonGroup.add(cosmetics);
        cosmetics.setForeground(new java.awt.Color(255, 255, 255));
        cosmetics.setText("cosmetics");
        cosmetics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosmeticsActionPerformed(evt);
            }
        });

        snacks.setBackground(new java.awt.Color(59, 103, 142));
        buttonGroup.add(snacks);
        snacks.setForeground(new java.awt.Color(255, 255, 255));
        snacks.setText("snacks");
        snacks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snacksActionPerformed(evt);
            }
        });

        toiletries.setBackground(new java.awt.Color(59, 103, 142));
        buttonGroup.add(toiletries);
        toiletries.setForeground(new java.awt.Color(255, 255, 255));
        toiletries.setText("toiletries");
        toiletries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toiletriesActionPerformed(evt);
            }
        });

        electronics.setBackground(new java.awt.Color(59, 103, 142));
        buttonGroup.add(electronics);
        electronics.setForeground(new java.awt.Color(255, 255, 255));
        electronics.setText("electronics");
        electronics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                electronicsActionPerformed(evt);
            }
        });

        clear.setText("Clear Selection");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(59, 103, 142));
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gobacvk.png"))); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        logout.setBackground(new java.awt.Color(59, 103, 142));
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout-icon.png"))); // NOI18N
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 27, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(clothes)
                                    .addComponent(grocery)
                                    .addComponent(cosmetics)
                                    .addComponent(snacks)
                                    .addComponent(electronics)
                                    .addComponent(toiletries))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(clear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(showInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(197, 197, 197)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(clothes)
                        .addGap(18, 18, 18)
                        .addComponent(grocery)
                        .addGap(18, 18, 18)
                        .addComponent(cosmetics)
                        .addGap(18, 18, 18)
                        .addComponent(snacks)
                        .addGap(18, 18, 18)
                        .addComponent(electronics)
                        .addGap(18, 18, 18)
                        .addComponent(toiletries)
                        .addGap(30, 30, 30)
                        .addComponent(clear)
                        .addGap(90, 90, 90))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showInventory)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showInventoryActionPerformed
        // TODO add your handling code here:
        inventoryController i = new inventoryController();
        i.fetch(inTable);

    }//GEN-LAST:event_showInventoryActionPerformed

    private void clothesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clothesActionPerformed
        // TODO add your handling code here:
        if (clothes.isSelected()) {
            inventoryController i = new inventoryController();
            i.catFetch(1, inTable);
        } else {
            inventoryController i = new inventoryController();
            i.fetch(inTable);

        }
    }//GEN-LAST:event_clothesActionPerformed

    private void groceryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groceryActionPerformed
        // TODO add your handling code here:
        if (grocery.isSelected()) {
            inventoryController i = new inventoryController();
            i.catFetch(2, inTable);
        } else {
            inventoryController i = new inventoryController();
            i.fetch(inTable);

        }
    }//GEN-LAST:event_groceryActionPerformed

    private void cosmeticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosmeticsActionPerformed
        // TODO add your handling code here:
        if (cosmetics.isSelected()) {
            inventoryController i = new inventoryController();
            i.catFetch(3, inTable);
        } else {
            inventoryController i = new inventoryController();
            i.fetch(inTable);

        }
    }//GEN-LAST:event_cosmeticsActionPerformed

    private void snacksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snacksActionPerformed
        // TODO add your handling code here:
        if (snacks.isSelected()) {
            inventoryController i = new inventoryController();
            i.catFetch(4, inTable);
        } else {
            inventoryController i = new inventoryController();
            i.fetch(inTable);

        }
    }//GEN-LAST:event_snacksActionPerformed

    private void electronicsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_electronicsActionPerformed
        // TODO add your handling code here:
        if (electronics.isSelected()) {
            inventoryController i = new inventoryController();
            i.catFetch(5, inTable);
        } else {
            inventoryController i = new inventoryController();
            i.fetch(inTable);

        }
    }//GEN-LAST:event_electronicsActionPerformed

    private void toiletriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toiletriesActionPerformed
        // TODO add your handling code here:
        if (toiletries.isSelected()) {
            inventoryController i = new inventoryController();
            i.catFetch(6, inTable);
        } else {
            inventoryController i = new inventoryController();
            i.fetch(inTable);

        }
    }//GEN-LAST:event_toiletriesActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:

        inventoryController i = new inventoryController();
        i.clearSelection(buttonGroup);
        i.fetch(inTable);

    }//GEN-LAST:event_clearActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        backACtionController b = new backACtionController();
        b.back();
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        logoutController i = new logoutController();
        i.logout();
        dispose();
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inventory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton clear;
    private javax.swing.JCheckBox clothes;
    private javax.swing.JCheckBox cosmetics;
    private javax.swing.JCheckBox electronics;
    private javax.swing.JCheckBox grocery;
    private javax.swing.JTable inTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logout;
    private javax.swing.JButton showInventory;
    private javax.swing.JCheckBox snacks;
    private javax.swing.JCheckBox toiletries;
    // End of variables declaration//GEN-END:variables
}
